SALON_DEFINITIONS = [
    ("Annonces", "salon_annonces"),
    ("Reglement", "salon_reglement"),
    ("Bienvenue", "salon_bienvenue"),
    ("Logs", "salon_logs"),
    ("Moderation", "salon_moderation"),
    ("Rapports", "salon_rapports"),
    ("General", "salon_general"),
    ("Economie", "salon_economie"),
    ("Boutique", "salon_boutique"),
    ("Exploration", "salon_exploration"),
    ("Combat", "salon_combat"),
    ("Duel / PvP", "salon_duel"),
    ("Peche-Chasse-Recolte", "salon_peche"),
    ("Casino", "salon_casino"),
    ("Equipages", "salon_equipages"),
    ("Marine", "salon_marine"),
    ("Revolutionnaires", "salon_revolutionnaires"),
    ("Classements", "salon_classements"),
    ("Quetes / Evenements", "salon_quetes"),
    ("Succes", "salon_succes"),
    ("Taverne (defis annexes)", "salon_taverne"),
    ("Regates", "salon_regates"),
    ("Chasse au tresor", "salon_tresor"),
    ("Creation de personnage", "salon_creation"),
    ("Guilde des metiers", "salon_guilde"),
    ("Carnet de bord (guide)", "salon_carnet"),
    ("Recompenses (daily/weekly/monthly)", "salon_recompenses"),
    ("Cartes a collectionner", "salon_cartes"),
    ("Entrainement (Haki)", "salon_entrainement"),
]
